package com.quoteflow.ai.insight;

public enum ReportingInsightType {
	BUSINESS_SUMMARY,
	PERIOD_COMPARISON,
	COLLECTIONS_COMPARISON,
	OUTSTANDING_ANALYSIS,
	TOP_OUTSTANDING_INVOICES,
	CUSTOMER_OUTSTANDING_ANALYSIS,
	PAYMENT_STATUS_ANALYSIS
}
